#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: joint_12/pose
        pose2d: joint_12/ground_pose
        child_frame_id: joint_12/base_link
        parent_frame_id: world
    '2':
        pose: joint_8/pose
        pose2d: joint_8/ground_pose
        child_frame_id: joint_8/base_link
        parent_frame_id: world
    '3':
        pose: joint_4/pose
        pose2d: joint_4/ground_pose
        child_frame_id: joint_4/base_link
        parent_frame_id: world
    '4':
        pose: joint_0/pose
        pose2d: joint_0/ground_pose
        child_frame_id: joint_0/base_link
        parent_frame_id: world
    '5':
        pose: obstacle_1/pose
        pose2d: obstacle_1/ground_pose
        child_frame_id: obstacle_1/base_link
        parent_frame_id: world
    '6':
        pose: obstacle_2/pose
        pose2d: obstacle_2/ground_pose
        child_frame_id: obstacle_2/base_link
        parent_frame_id: world
    '7':
        pose: obstacle_3/pose
        pose2d: obstacle_3/ground_pose
        child_frame_id: obstacle_3/base_link
        parent_frame_id: world    

optitrack_config:
        multicast_address: 224.0.0.1
